name: Maven CI Workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B --no-transfer-progress install
      - name: Test
        run: mvn test
